---
new_page_extension: html
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: index.html
  label: New Directory
  create: all
  match: "**/*"
  templates:
  - landing-page-template
- type: document
  path: document
  label: Document
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - landing-page-template
  - landing-page
- type: jekyll-posts
  label: Posts
  create: all
upload_dir: images
public_path: images
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
